# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: COVID-19 in Care Homes
email: p.dutey-magni@ucl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Weekly surveillance reports on rates of infections in an English
  network of xxx care homes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  peterdutey

# Build settings
theme: jekyll-docs-theme
remote_theme: allejo/jekyll-docs-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme


links:
  header:
    - title: Privacy
      icon: shield-alt
      url: privacy
  homepage:
    - title: EWAC calculator
      icon: arrow-circle-right
      url: questionnaire
#  footer:
#    - title: GitHub
#      icon: github
#      brand: true
#      url: https://github.com/peterdutey/ewac-resources
#    - title: Issues
#      icon: bug
#      url: https://github.com/peterdutey/ewac-resources/issues?state=open
#    - title: Academic paper
#      icon: file-alt
#      url: https://iris.ucl.ac.uk/iris/browse/profile?upi=PFDUT15


#license:
#  software: GNU GPLv3
#  software_url: https://www.gnu.org/licenses/gpl-3.0.en.html
#
#  docs: CC BY 3.0
#  docs_url: https://creativecommons.org/licenses/by/3.0/


ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#003087"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#003087" # "#080331"
      color2: "#005EB8" #"#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
